services:
  postgres:
    image: postgres:16
    container_name: battleshipgame-postgres
    environment:
      POSTGRES_DB: battleshipgame
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - battleshipgame-pgdata:/var/lib/postgresql/data

volumes:
  battleshipgame-pgdata:
